enum L10nSimplifiedChinese {
    static let strings: [String: String] = [
        "%@ contributions": "%@ 次贡献",
        "%@ blocked": "%@ 已阻塞",
        "%@ left": "剩余 %@",
        "%@ percent remaining": "剩余百分之 %@",
        "Accounts": "账号",
        "Account Status": "账号状态",
        "Activity feed": "活动流",
        "Activity heatmap for %@": "%@ 的活动热力图",
        "Activity": "活动",
        "Add": "添加",
        "Add or Update Account": "添加或更新账号",
        "Accent tone": "强调色",
        "Advanced": "高级",
        "All": "全部",
        "All Labels": "全部标签",
        "All activity": "全部活动",
        "AI Summaries": "AI 摘要",
        "AI request URL reset to default.": "AI 请求 URL 已重置为默认值。",
        "AI request URL saved.": "AI 请求 URL 已保存。",
        "AI summaries unavailable: %@": "AI 摘要不可用：%@",
        "About": "关于",
        "About RepoPeek": "关于 RepoPeek",
        "1 month": "1 个月",
        "3 months": "3 个月",
        "6 months": "6 个月",
        "12 months": "12 个月",
        "Automatically opens RepoPeek when you start your Mac.": "Mac 启动时自动打开 RepoPeek。",
        "Authentication": "认证",
        "Base URL": "基础 URL",
        "Base URL must be a valid https:// URL with a trusted certificate.": "基础 URL 必须是有效的 https:// 地址，并使用可信证书。",
        "Branch list failed": "分支列表加载失败",
        "Branches": "分支",
        "blocked": "已阻塞",
        "Budget Model": "配额模型",
        "Cancel": "取消",
        "Card density": "卡片密度",
        "Check Token": "检查令牌",
        "Checking token...": "正在检查令牌...",
        "Checkout Repo": "检出仓库",
        "Checkout failed": "检出失败",
        "Changelog": "变更日志",
        "Choose a Local Projects folder in Settings to enable checkout.": "在设置中选择本地项目文件夹后才能检出。",
        "Choose the main menu shortcut for opening Issue Navigator.": "选择用于打开议题导航的主菜单快捷键。",
        "Changelog failed: %@": "变更日志加载失败：%@",
        "Claude Agent": "Claude Agent",
        "Clear OpenAI API key": "清除 OpenAI API key",
        "Clear shortcut": "清除快捷键",
        "Click a field, then press the shortcut. Delete clears it.": "点击输入框后按下快捷键。按 Delete 可清除。",
        "Clone a repository or set your projects folder in Settings.": "克隆仓库，或在设置中指定项目目录。",
        "Commented": "已评论",
        "Comfortable": "舒适",
        "Commits": "提交",
        "Compact": "紧凑",
        "Connect your GitLab account to load pins and activity.": "连接 GitLab 账号以加载固定仓库和活动。",
        "Contribution Header": "贡献概览",
        "Contribution greens": "贡献绿色",
        "Contribution greens keep the classic contribution palette; System accent follows your macOS accent color.": "贡献绿色保留经典贡献图配色；系统强调色会跟随 macOS 强调色。",
        "Contributors": "贡献者",
        "Copy Update Diagnostics": "复制更新诊断",
        "Could not find %@.": "找不到 %@。",
        "Create a token on GitLab": "在 GitLab 创建令牌",
        "Create branch": "创建分支",
        "Create branch failed": "创建分支失败",
        "Create Branch…": "创建分支…",
        "Create worktree": "创建工作树",
        "Create worktree failed": "创建工作树失败",
        "Create Worktree…": "创建工作树…",
        "Current Blocker": "当前阻塞",
        "Current Status": "当前状态",
        "Customize the menu layout and repo submenu items.": "自定义菜单布局和仓库子菜单项目。",
        "Default browser": "默认浏览器",
        "Detached": "分离",
        "Details": "详情",
        "Dirty %@": "未提交 %@",
        "Display": "显示",
        "Endpoint cooldown": "端点冷却中",
        "Endpoint Cooldowns": "端点冷却",
        "Enterprise / Import": "企业/导入",
        "Enter a branch name for the new worktree.": "输入新工作树使用的分支名。",
        "Enter a new branch name.": "输入新分支名。",
        "Enter the folder path for the new worktree.": "输入新工作树的文件夹路径。",
        "Error: %@": "错误：%@",
        "Each GitLab account uses its own Personal Access Token. Enabled accounts are refreshed together.": "每个 GitLab 账号使用独立的个人访问令牌。已启用的账号会一起刷新。",
        "Each GitLab instance uses its own Personal Access Token. Enabled accounts are refreshed together.": "每个 GitLab 实例使用独立的个人访问令牌。已启用的账号会一起刷新。",
        "Enabled": "启用",
        "Fetched %@": "已获取 %@",
        "Filters apply to repo lists and search. 'Show only my repositories' hides repos owned by organizations and other users.": "过滤条件会应用到仓库列表和搜索。“只显示我的仓库”会隐藏组织和其他用户拥有的仓库。",
        "Failed to load": "加载失败",
        "Failed to load branches": "分支加载失败",
        "Failed to load local branches": "本地分支加载失败",
        "Failed to load worktrees": "工作树加载失败",
        "Failed: %@": "失败：%@",
        "Fast issue and merge request search": "快速搜索议题和合并请求",
        "Forks": "派生",
        "General": "通用",
        "GitLab Accounts": "GitLab 账号",
        "GitLab Application": "GitLab 应用",
        "GitLab API Status": "GitLab API 状态",
        "GitLab API budget is tied to the PAT owner.": "GitLab API 配额绑定到 PAT 所属用户。",
        "GitLab API Status, %@": "GitLab API 状态，%@",
        "GitLab rate limit": "GitLab 限流",
        "GitLab sign-in action": "GitLab 登录操作",
        "Hard reset %@?": "硬重置 %@？",
        "Heatmap window": "热力图窗口",
        "Heatmap": "热力图",
        "Heatmap header + submenu": "热力图概览和子菜单",
        "Hide": "隐藏",
        "Hide Repo": "隐藏仓库",
        "Include archived repositories": "包含已归档仓库",
        "Include forked repositories": "包含 fork 仓库",
        "Inline markdown preview": "内联 Markdown 预览",
        "Inline": "内联",
        "Invalid repository": "无效仓库",
        "Invalid repository name": "无效仓库名",
        "Invalid repository URL.": "无效仓库 URL。",
        "Interface language": "界面语言",
        "Issues %d": "议题 %d",
        "Issues: %d • Owner: %@": "议题：%d · 所有者：%@",
        "Issues, MRs, pushes, and comments.": "议题、MR、推送和评论。",
        "Issue Navigator": "议题导航",
        "Issue Navigator…": "议题导航…",
        "Issues": "议题",
        "Latest activity": "最近活动",
        "Latest event": "最近事件",
        "Latest: %@": "最新：%@",
        "Latest release %@.": "最新发布 %@。",
        "Language": "语言",
        "Launch at login": "登录时启动",
        "Loading repositories…": "正在加载仓库…",
        "Loading…": "正在加载…",
        "Local": "本地",
        "Local checkout": "本地检出",
        "Local Repo Status": "本地仓库状态",
        "Login state banner": "登录状态横幅",
        "Main Menu": "主菜单",
        "Manual GitLab and local project refresh": "手动刷新 GitLab 和本地项目",
        "Menu Filters": "菜单过滤器",
        "Menu sort": "菜单排序",
        "Merge request notifications": "合并请求通知",
        "Merge request updates": "合并请求更新",
        "Merge Requests": "合并请求",
        "Mine": "我的",
        "Model": "模型",
        "More Activity…": "更多活动…",
        "More Commits…": "更多提交…",
        "More Labels…": "更多标签…",
        "Most MRs": "最多 MR",
        "Most issues": "最多议题",
        "Most stars": "最多星标",
        "Move Down": "下移",
        "Move Up": "上移",
        "Move down": "下移",
        "Move up": "上移",
        "MRs": "MR",
        "My activity": "我的活动",
        "Name": "名称",
        "New comments": "新评论",
        "New merge requests": "新合并请求",
        "No GitLab accounts configured.": "尚未配置 GitLab 账号。",
        "No active GitLab blocker.": "当前没有 GitLab 阻塞。",
        "No assets": "没有资源",
        "No branches": "没有分支",
        "No changelog found": "未找到变更日志",
        "No commits": "没有提交",
        "No contributors": "没有贡献者",
        "No local branches": "没有本地分支",
        "No local repositories": "没有本地仓库",
        "No matching issues": "没有匹配的议题",
        "No matching merge requests": "没有匹配的合并请求",
        "No open issues": "没有打开的议题",
        "No open merge requests": "没有打开的合并请求",
        "No pinned repositories": "没有固定仓库",
        "No pipelines": "没有流水线",
        "No rate-limit data yet": "暂无限流数据",
        "No recent activity": "暂无最近活动",
        "No releases": "没有发布",
        "No repositories match this filter": "没有匹配此过滤器的仓库",
        "No repositories yet": "暂无仓库",
        "No tags": "没有标签",
        "No token stored.": "未保存令牌。",
        "No worktrees": "没有工作树",
        "Notifications": "通知",
        "OK": "确定",
        "Open %@ in GitLab": "在 GitLab 打开 %@",
        "Open %@ refs in Issue Navigator…": "在议题导航中打开 %@ 个引用…",
        "Open Activity": "打开活动",
        "Open Branches": "打开分支",
        "Open Commits": "打开提交",
        "Open Contributors": "打开贡献者",
        "Open Issues": "打开议题",
        "Open Latest Release": "打开最新发布",
        "Open Merge Requests": "打开合并请求",
        "Open Settings": "打开设置",
        "Open on GitLab": "在 GitLab 打开",
        "OpenAI Responses": "OpenAI Responses",
        "OpenAI API key": "OpenAI API key",
        "OpenAI API key cleared.": "OpenAI API key 已清除。",
        "OpenAI API key saved.": "OpenAI API key 已保存。",
        "OpenAI API key stored in Keychain.": "OpenAI API key 已保存到钥匙串。",
        "Open Pipelines": "打开流水线",
        "Open Release": "打开发布",
        "Open Releases": "打开发布",
        "Open repository in browser": "在浏览器中打开仓库",
        "Open Tags": "打开标签",
        "Open in Finder": "在 Finder 中打开",
        "Open in GitLab": "在 GitLab 打开",
        "Open in Terminal": "在终端中打开",
        "Other GitLab clients may still work if they use a different token, but the same user quota can still be shared.": "其他 GitLab 客户端如果使用不同令牌仍可能可用，但同一用户配额仍可能共享。",
        "Other Resources": "其他资源",
        "Paste key": "粘贴 key",
        "Personal Access Token": "个人访问令牌",
        "Pin": "固定",
        "Pin a repository to see activity here.": "固定仓库后可在这里查看活动。",
        "Pin/Unpin": "固定/取消固定",
        "Pinned": "固定",
        "Pinned/hidden filter chips": "固定/隐藏过滤控件",
        "Pipelines": "流水线",
        "Preferences": "偏好设置",
        "Preferences…": "偏好设置…",
        "Preview truncated": "预览已截断",
        "Provider": "提供方",
        "Rate limited until %@": "限流至 %@",
        "Rate limit reset: %@": "限流重置：%@",
        "Rate limit resets %@": "限流将于 %@ 重置",
        "Rate-limit or error banner": "限流或错误横幅",
        "Rebase": "变基",
        "Rebase failed": "变基失败",
        "Quit RepoPeek": "退出 RepoPeek",
        "Recently active": "最近活跃",
        "Release %@": "发布 %@",
        "Releases": "发布",
        "Remove": "移除",
        "Remove Rule": "移除规则",
        "Repositories": "仓库",
        "REST Core": "REST 核心",
        "REST Search": "REST 搜索",
        "Repository Cards": "仓库卡片",
        "Repository List": "仓库列表",
        "Repository name": "仓库名称",
        "Repositories shown": "显示仓库数",
        "Repo cards + inline heatmap": "仓库卡片和内联热力图",
        "Repository rows + inline heatmap": "仓库行和内联热力图",
        "Repo heatmap submenu": "仓库热力图子菜单",
        "Repo Submenu": "仓库子菜单",
        "Repository heatmap": "仓库热力图",
        "Repository heatmaps show recent commit activity for each repository.": "仓库热力图展示每个仓库最近的提交活动。",
        "Request URL": "请求 URL",
        "Request URL must be a valid http:// or https:// URL.": "请求 URL 必须是有效的 http:// 或 https:// 地址。",
        "Required GitLab scopes: api, read_user, read_repository": "需要 GitLab 权限范围：api、read_user、read_repository",
        "Required": "必需",
        "Required · %@": "必需 · %@",
        "Reset": "重置",
        "Reset failed": "重置失败",
        "Reset to Defaults": "恢复默认",
        "reset %@": "已于 %@ 重置",
        "resets %@": "%@ 后重置",
        "Restart to Update": "重启以更新",
        "Restart to update": "重启以更新",
        "Reviewed": "已审查",
        "Review requested": "请求审查",
        "retry %@": "%@ 后重试",
        "Save Account": "保存账号",
        "sampled %@": "采样于 %@",
        "Settings": "设置",
        "Set a local projects folder": "设置本地项目文件夹",
        "Search, filters, sort, and refresh": "搜索、过滤、排序和刷新",
        "Scoped to pinned repositories. The first refresh records the current state without sending notifications.": "仅作用于固定仓库。首次刷新会记录当前状态，不发送通知。",
        "Shared GitLab user budget; RepoPeek and other PATs for this account can spend this API quota. Extra tokens do not create extra user quota.": "共享 GitLab 用户配额；RepoPeek 和此账号的其他 PAT 都会消耗同一 API 配额。额外令牌不会创建额外用户配额。", // swiftlint:disable:this line_length
        "Show contribution header": "显示贡献概览",
        "Show GitLab rate-limit count in menu bar": "在菜单栏显示 GitLab 限流余量",
        "Show fewer repositories": "减少显示仓库数",
        "Show more repositories": "增加显示仓库数",
        "Show only my repositories": "只显示我的仓库",
        "Shown only when GitLab API is blocked": "仅在 GitLab API 被阻塞时显示",
        "Shown when an update is ready": "有更新可用时显示",
        "Sign In": "登录",
        "Sign in to GitLab": "登录 GitLab",
        "Sign in to load changelog": "登录后加载变更日志",
        "Sign in to load branches": "登录后加载分支",
        "Sign in to load items": "登录后加载项目",
        "Sign in to see your repositories": "登录后查看仓库",
        "Sign in to view": "登录后查看",
        "Signing in...": "正在登录...",
        "Signing in…": "正在登录…",
        "Sort by %@": "按 %@ 排序",
        "Sort by %@. Click to cycle.": "按 %@ 排序。点击切换。",
        "Stars": "星标",
        "Status Banner": "状态横幅",
        "Stored Blockers": "已保存阻塞",
        "Switch Worktree": "切换工作树",
        "Switch branch failed": "切换分支失败",
        "Sync": "同步",
        "Sync + dirty state": "同步和未提交状态",
        "Sync failed": "同步失败",
        "Submenu": "子菜单",
        "System": "跟随系统",
        "System accent": "系统强调色",
        "Tags": "标签",
        "This will discard uncommitted changes and reset to %@.": "这会丢弃未提交更改，并重置到 %@。",
        "Timed out": "超时",
        "Timed out after %@s": "%@ 秒后超时",
        "Token": "令牌",
        "Token invalid: %@": "令牌无效：%@",
        "Token is valid.": "令牌有效。",
        "Token status not checked yet.": "令牌状态尚未检查。",
        "Tracking %@": "跟踪 %@",
        "Try All or a different filter.": "尝试“全部”或其他过滤器。",
        "Updating repositories…": "正在更新仓库…",
        "Updating…": "更新中…",
        "Update diagnostics copied.": "更新诊断已复制。",
        "Use default request URL": "使用默认请求 URL",
        "Uses Claude Agent CLI print-mode protocol to summarize merge requests in Issue Navigator.": "使用 Claude Agent CLI print 模式协议总结议题导航中的合并请求。",
        "Uses local Claude Agent CLI authentication.": "使用本地 Claude Agent CLI 认证。",
        "Uses OpenAI Responses-compatible API to summarize merge requests in Issue Navigator.": "使用 OpenAI Responses 兼容 API 总结议题导航中的合并请求。",
        "Using custom request URL: %@": "使用自定义请求 URL：%@",
        "Using default request URL: %@": "使用默认请求 URL：%@",
        "Unpin": "取消固定",
        "Updated %@": "更新于 %@",
        "Upstream %@": "上游 %@",
        "Visible": "可见",
        "View All": "查看全部",
        "When clicked": "点击时",
        "Work": "待办",
        "Worktree %@": "工作树 %@",
        "Worktree folder": "工作树文件夹",
        "Worktree list failed": "工作树列表加载失败",
        "Worktree missing": "工作树不存在",
        "1 minute": "1 分钟",
        "2 minutes": "2 分钟",
        "5 minutes": "5 分钟",
        "15 minutes": "15 分钟",
        "30 minutes": "30 分钟",
        "1 hour": "1 小时",
        "6 hours": "6 小时",
        "12 hours": "12 小时",
        "1 day": "1 天",
        "%d level": "%d 级",
        "%d levels": "%d 级",
        "%d of %d repositories, %d pinned, %d hidden": "显示 %d/%d 个仓库，%d 个已固定，%d 个已隐藏",
        "%d repositories, %d loaded, %d pinned, %d hidden": "%d 个仓库，%d 个已加载，%d 个已固定，%d 个已隐藏",
        "%d rows": "%d 行",
        "%@ issues": "%@ 个议题",
        "Action": "动作",
        "Add Repo": "添加仓库",
        "Add Rule": "添加规则",
        "Activity %@": "活动 %@",
        "Archived": "已归档",
        "Auto-sync clean repos": "自动同步干净仓库",
        "Branch %@": "分支 %@",
        "Browse repositories RepoPeek can access and choose what stays pinned or hidden.": "浏览 RepoPeek 可访问的仓库，并选择固定或隐藏哪些仓库。",
        "Built %@": "构建于 %@",
        "Check for updates automatically": "自动检查更新",
        "Check for Updates…": "检查更新…",
        "Choose": "选择",
        "Choose…": "选择…",
        "Choose Repo…": "选择仓库…",
        "Change expression less often": "降低表情切换频率",
        "Change expression more often": "提高表情切换频率",
        "Clear project folder": "清除项目文件夹",
        "Clear search": "清空搜索",
        "Cloners": "克隆者",
        "Controls how often idle menu bar icon expressions change.": "控制空闲状态下菜单栏图标表情切换频率。",
        "Controls how often RepoPeek refreshes GitLab data.": "控制 RepoPeek 刷新 GitLab 数据的频率。",
        "Debug": "调试",
        "Developer-only diagnostics and experimental tools.": "仅开发者使用的诊断和实验工具。",
        "Enable debug tools": "启用调试工具",
        "Enter group path": "输入组路径",
        "Enter group/subgroup before adding a rule.": "输入组/子组后才能添加规则。",
        "Enter owner/name before adding a rule.": "输入所有者/名称后才能添加规则。",
        "Enter repo name": "输入仓库名",
        "Engagement": "参与",
        "Fetch interval": "拉取间隔",
        "Fork": "Fork",
        "Found %d local repos · %d match GitLab data.": "找到 %d 个本地仓库 · %d 个匹配 GitLab 数据。",
        "Found %d local repos.": "找到 %d 个本地仓库。",
        "Ghostty opens in": "Ghostty 打开方式",
        "GitLab Archives": "GitLab 归档",
        "GitLab References": "GitLab 引用",
        "GitLab URLs, issue numbers, commit hashes": "GitLab URL、议题编号、提交哈希",
        "Group": "组",
        "Group Hidden": "组隐藏",
        "Group path": "组路径",
        "Group Rule": "组规则",
        "Hidden": "隐藏",
        "Hide Group": "隐藏组",
        "Hide Repository": "隐藏仓库",
        "imported %@": "导入于 %@",
        "Local Projects": "本地项目",
        "Manual": "手动",
        "Matches": "匹配",
        "Menubar glance at GitLab repos: CI, issues/MRs, releases, and activity.": "在菜单栏快速查看 GitLab 仓库的 CI、议题/MR、发布和活动。",
        "Merge requests %d": "合并请求 %d",
        "New Window": "新窗口",
        "No GitLab archives configured.": "尚未配置 GitLab 归档。",
        "No repositories found yet. Re-choose the folder to grant access.": "尚未找到仓库。请重新选择文件夹以授予访问权限。",
        "No repositories found yet.": "尚未找到仓库。",
        "Not set": "未设置",
        "not ready": "未就绪",
        "now": "刚刚",
        "group/subgroup": "组/子组",
        "owner/name": "所有者/名称",
        "owner/repo, URL, or local path": "所有者/仓库、URL 或本地路径",
        "Pin a repository": "固定仓库",
        "Pin Repository": "固定仓库",
        "Pipeline %@": "流水线 %@",
        "Point RepoPeek at a snapshot repository. RepoPeek manages the imported database internally and uses it only when GitLab is rate limited.": "将 RepoPeek 指向一个快照仓库。RepoPeek 会在内部管理导入数据库，并仅在 GitLab 限流时使用。", // swiftlint:disable:this line_length
        "Preferred Terminal": "首选终端",
        "Press shortcut": "按下快捷键",
        "Project folder": "项目文件夹",
        "Pull and import archive": "拉取并导入归档",
        "pushed %@": "推送于 %@",
        "ready": "就绪",
        "Refresh": "刷新",
        "Refresh interval": "刷新间隔",
        "Refresh Now": "立即刷新",
        "Remove archive": "移除归档",
        "Repo": "仓库",
        "repo: %@": "仓库：%@",
        "Repository": "仓库",
        "Repository path": "仓库路径",
        "Repository rules use owner/name. Group rules use namespace paths such as group/subgroup and hide everything below that path.": "仓库规则使用所有者/名称。组规则使用类似 组/子组 的命名空间路径，并隐藏该路径下的所有仓库。", // swiftlint:disable:this line_length
        "Rule": "规则",
        "Rule Type": "规则类型",
        "Rules use owner/name. Pinned repositories are prioritized in the menu; hidden repositories are removed from menu lists. Set Visible removes a rule.": "规则使用所有者/名称。固定仓库会在菜单中优先显示；隐藏仓库会从菜单列表中移除；设为可见会删除规则。", // swiftlint:disable:this line_length
        "Rescan local projects": "重新扫描本地项目",
        "Scope": "范围",
        "Scan depth": "扫描深度",
        "Scanning…": "正在扫描…",
        "Scans up to the configured depth under the folder, fetches periodically, and can fast-forward pull clean repos.": "在配置深度内扫描文件夹，定期拉取，并可快进同步干净仓库。",
        "Save": "保存",
        "Search current list": "搜索当前列表",
        "Search repositories": "搜索仓库",
        "Set Visible": "设为可见",
        "sec.": "秒",
        "Show dirty files in menu": "在菜单中显示未提交文件",
        "Shows the best cached or live match in a separate menu bar item when a copied reference resolves.": "复制的引用解析成功时，在单独的菜单栏项目中显示最佳缓存或实时匹配。",
        "Shortcuts": "快捷键",
        "Summarize merge requests": "总结合并请求",
        "Summarizing merge requests…": "正在总结合并请求…",
        "Status icon expression": "状态栏图标表情",
        "Sync %@": "同步 %@",
        "Tab": "标签页",
        "Updates unavailable in this build.": "此构建不支持更新。",
        "Updated": "更新",
        "Uses OpenAI Responses API to summarize merge requests in Issue Navigator.": "使用 OpenAI Responses API 总结议题导航中的合并请求。",
        "Use archives when rate limited": "限流时使用归档",
        "Version %@": "版本 %@",
        "Visibility": "可见性",
        "Visitors": "访问者",
        "Watch copied GitLab references": "监听复制的 GitLab 引用",
        "All Repositories": "全部仓库",
        "Back": "返回",
        "Clipboard: %@": "剪贴板：%@",
        "Closed": "已关闭",
        "Copy": "复制",
        "Copy selected result URL": "复制选中结果 URL",
        "Commit": "提交",
        "Copy URL": "复制 URL",
        "Draft": "草稿",
        "Issue": "议题",
        "Issues + MRs": "议题 + MR",
        "Issue Navigator shortcut": "议题导航快捷键",
        "Items": "事项",
        "Keyboard Shortcuts": "键盘快捷键",
        "Loading recent issues and merge requests.": "正在加载最近的议题和合并请求。",
        "match": "条匹配",
        "matches": "条匹配",
        "None": "无",
        "Merged": "已合并",
        "Merge Request": "合并请求",
        "No matches": "无匹配",
        "No matching issues or merge requests.": "没有匹配的议题或合并请求。",
        "No recent issues or merge requests in this scope.": "此范围内没有最近的议题或合并请求。",
        "No recent items in this scope.": "此范围内没有最近项目。",
        "Open": "打开",
        "Open in Browser": "在浏览器中打开",
        "Open selected result in browser": "在浏览器中打开选中结果",
        "Pick a result": "选择一个结果",
        "Pre": "预发布",
        "Recent subscribed and accessible items": "最近订阅和可访问的项目",
        "References in pasted order": "按粘贴顺序显示引用",
        "Refresh results": "刷新结果",
        "Search by title, URL, owner/repo#number, or commit SHA.": "按标题、URL、所有者/仓库#编号或提交 SHA 搜索。",
        "Search failed": "搜索失败",
        "Search the current clipboard reference": "搜索当前剪贴板引用",
        "Search issues and merge requests": "搜索议题和合并请求",
        "Searching…": "正在搜索…",
        "Showing recent items; type at least %d characters to search.": "正在显示最近项目；输入至少 %d 个字符后搜索。",
        "Type at least %d characters, or paste a GitLab reference.": "输入至少 %d 个字符，或粘贴 GitLab 引用。",
        "Updated newest first": "按最新更新排序",
        "Using %@": "正在使用 %@",
        "Use Clipboard": "使用剪贴板",
        "Workflow Run": "流水线运行",
        "Work GitLab": "工作 GitLab"
    ]
}
