enum L10nEnglish {
    static let strings: [String: String] = [
        "%@ contributions": "%@ contributions",
        "%@ blocked": "%@ blocked",
        "%@ left": "%@ left",
        "%@ percent remaining": "%@ percent remaining",
        "Accounts": "Accounts",
        "Account Status": "Account Status",
        "Activity feed": "Activity feed",
        "Activity heatmap for %@": "Activity heatmap for %@",
        "Activity": "Activity",
        "Add": "Add",
        "Add or Update Account": "Add or Update Account",
        "Accent tone": "Accent tone",
        "Advanced": "Advanced",
        "All": "All",
        "All Labels": "All Labels",
        "All activity": "All activity",
        "AI Summaries": "AI Summaries",
        "AI request URL reset to default.": "AI request URL reset to default.",
        "AI request URL saved.": "AI request URL saved.",
        "AI summaries unavailable: %@": "AI summaries unavailable: %@",
        "About": "About",
        "About RepoPeek": "About RepoPeek",
        "1 month": "1 month",
        "3 months": "3 months",
        "6 months": "6 months",
        "12 months": "12 months",
        "Automatically opens RepoPeek when you start your Mac.": "Automatically opens RepoPeek when you start your Mac.",
        "Authentication": "Authentication",
        "Base URL": "Base URL",
        "Base URL must be a valid https:// URL with a trusted certificate.": "Base URL must be a valid https:// URL with a trusted certificate.",
        "Branch list failed": "Branch list failed",
        "Branches": "Branches",
        "blocked": "blocked",
        "Budget Model": "Budget Model",
        "Cancel": "Cancel",
        "Card density": "Card density",
        "Check Token": "Check Token",
        "Checking token...": "Checking token...",
        "Checkout Repo": "Checkout Repo",
        "Checkout failed": "Checkout failed",
        "Changelog": "Changelog",
        "Choose a Local Projects folder in Settings to enable checkout.": "Choose a Local Projects folder in Settings to enable checkout.",
        "Choose the main menu shortcut for opening Issue Navigator.": "Choose the main menu shortcut for opening Issue Navigator.",
        "Changelog failed: %@": "Changelog failed: %@",
        "Claude Agent": "Claude Agent",
        "Clear OpenAI API key": "Clear OpenAI API key",
        "Clear shortcut": "Clear shortcut",
        "Click a field, then press the shortcut. Delete clears it.": "Click a field, then press the shortcut. Delete clears it.",
        "Clone a repository or set your projects folder in Settings.": "Clone a repository or set your projects folder in Settings.",
        "Commented": "Commented",
        "Comfortable": "Comfortable",
        "Commits": "Commits",
        "Compact": "Compact",
        "Connect your GitLab account to load pins and activity.": "Connect your GitLab account to load pins and activity.",
        "Contribution Header": "Contribution Header",
        "Contribution greens": "Contribution greens",
        "Contribution greens keep the classic contribution palette; System accent follows your macOS accent color.": "Contribution greens keep the classic contribution palette; System accent follows your macOS accent color.", // swiftlint:disable:this line_length
        "Contributors": "Contributors",
        "Copy Update Diagnostics": "Copy Update Diagnostics",
        "Could not find %@.": "Could not find %@.",
        "Create a token on GitLab": "Create a token on GitLab",
        "Create branch": "Create branch",
        "Create branch failed": "Create branch failed",
        "Create Branch…": "Create Branch…",
        "Create worktree": "Create worktree",
        "Create worktree failed": "Create worktree failed",
        "Create Worktree…": "Create Worktree…",
        "Current Blocker": "Current Blocker",
        "Current Status": "Current Status",
        "Customize the menu layout and repo submenu items.": "Customize the menu layout and repo submenu items.",
        "Default browser": "Default browser",
        "Detached": "Detached",
        "Details": "Details",
        "Dirty %@": "Dirty %@",
        "Display": "Display",
        "Endpoint cooldown": "Endpoint cooldown",
        "Endpoint Cooldowns": "Endpoint Cooldowns",
        "Enterprise / Import": "Enterprise / Import",
        "Enter a branch name for the new worktree.": "Enter a branch name for the new worktree.",
        "Enter a new branch name.": "Enter a new branch name.",
        "Enter the folder path for the new worktree.": "Enter the folder path for the new worktree.",
        "Error: %@": "Error: %@",
        "Each GitLab account uses its own Personal Access Token. Enabled accounts are refreshed together.": "Each GitLab account uses its own Personal Access Token. Enabled accounts are refreshed together.", // swiftlint:disable:this line_length
        "Each GitLab instance uses its own Personal Access Token. Enabled accounts are refreshed together.": "Each GitLab instance uses its own Personal Access Token. Enabled accounts are refreshed together.", // swiftlint:disable:this line_length
        "Enabled": "Enabled",
        "Fetched %@": "Fetched %@",
        "Filters apply to repo lists and search. 'Show only my repositories' hides repos owned by organizations and other users.": "Filters apply to repo lists and search. 'Show only my repositories' hides repos owned by organizations and other users.", // swiftlint:disable:this line_length
        "Failed to load": "Failed to load",
        "Failed to load branches": "Failed to load branches",
        "Failed to load local branches": "Failed to load local branches",
        "Failed to load worktrees": "Failed to load worktrees",
        "Failed: %@": "Failed: %@",
        "Fast issue and merge request search": "Fast issue and merge request search",
        "Forks": "Forks",
        "General": "General",
        "GitLab Accounts": "GitLab Accounts",
        "GitLab Application": "GitLab Application",
        "GitLab API Status": "GitLab API Status",
        "GitLab API budget is tied to the PAT owner.": "GitLab API budget is tied to the PAT owner.",
        "GitLab API Status, %@": "GitLab API Status, %@",
        "GitLab rate limit": "GitLab rate limit",
        "GitLab sign-in action": "GitLab sign-in action",
        "Hard reset %@?": "Hard reset %@?",
        "Heatmap window": "Heatmap window",
        "Heatmap": "Heatmap",
        "Heatmap header + submenu": "Heatmap header + submenu",
        "Hide": "Hide",
        "Hide Repo": "Hide Repo",
        "Include archived repositories": "Include archived repositories",
        "Include forked repositories": "Include forked repositories",
        "Inline markdown preview": "Inline markdown preview",
        "Inline": "Inline",
        "Invalid repository": "Invalid repository",
        "Invalid repository name": "Invalid repository name",
        "Invalid repository URL.": "Invalid repository URL.",
        "Interface language": "Interface language",
        "Issues %d": "Issues %d",
        "Issues: %d • Owner: %@": "Issues: %d • Owner: %@",
        "Issues, MRs, pushes, and comments.": "Issues, MRs, pushes, and comments.",
        "Issue Navigator": "Issue Navigator",
        "Issue Navigator…": "Issue Navigator…",
        "Issues": "Issues",
        "Latest activity": "Latest activity",
        "Latest event": "Latest event",
        "Latest: %@": "Latest: %@",
        "Latest release %@.": "Latest release %@.",
        "Language": "Language",
        "Launch at login": "Launch at login",
        "Loading repositories…": "Loading repositories…",
        "Loading…": "Loading…",
        "Local": "Local",
        "Local checkout": "Local checkout",
        "Local Repo Status": "Local Repo Status",
        "Login state banner": "Login state banner",
        "Main Menu": "Main Menu",
        "Manual GitLab and local project refresh": "Manual GitLab and local project refresh",
        "Menu Filters": "Menu Filters",
        "Menu sort": "Menu sort",
        "Merge request notifications": "Merge request notifications",
        "Merge request updates": "Merge request updates",
        "Merge Requests": "Merge Requests",
        "Mine": "Mine",
        "Model": "Model",
        "More Activity…": "More Activity…",
        "More Commits…": "More Commits…",
        "More Labels…": "More Labels…",
        "Most MRs": "Most MRs",
        "Most issues": "Most issues",
        "Most stars": "Most stars",
        "Move Down": "Move Down",
        "Move Up": "Move Up",
        "Move down": "Move down",
        "Move up": "Move up",
        "MRs": "MRs",
        "My activity": "My activity",
        "Name": "Name",
        "New comments": "New comments",
        "New merge requests": "New merge requests",
        "No GitLab accounts configured.": "No GitLab accounts configured.",
        "No active GitLab blocker.": "No active GitLab blocker.",
        "No assets": "No assets",
        "No branches": "No branches",
        "No changelog found": "No changelog found",
        "No commits": "No commits",
        "No contributors": "No contributors",
        "No local branches": "No local branches",
        "No local repositories": "No local repositories",
        "No matching issues": "No matching issues",
        "No matching merge requests": "No matching merge requests",
        "No open issues": "No open issues",
        "No open merge requests": "No open merge requests",
        "No pinned repositories": "No pinned repositories",
        "No pipelines": "No pipelines",
        "No rate-limit data yet": "No rate-limit data yet",
        "No recent activity": "No recent activity",
        "No releases": "No releases",
        "No repositories match this filter": "No repositories match this filter",
        "No repositories yet": "No repositories yet",
        "No tags": "No tags",
        "No token stored.": "No token stored.",
        "No worktrees": "No worktrees",
        "Notifications": "Notifications",
        "OK": "OK",
        "Open %@ in GitLab": "Open %@ in GitLab",
        "Open %@ refs in Issue Navigator…": "Open %@ refs in Issue Navigator…",
        "Open Activity": "Open Activity",
        "Open Branches": "Open Branches",
        "Open Commits": "Open Commits",
        "Open Contributors": "Open Contributors",
        "Open Issues": "Open Issues",
        "Open Latest Release": "Open Latest Release",
        "Open Merge Requests": "Open Merge Requests",
        "Open Settings": "Open Settings",
        "Open on GitLab": "Open on GitLab",
        "OpenAI Responses": "OpenAI Responses",
        "OpenAI API key": "OpenAI API key",
        "OpenAI API key cleared.": "OpenAI API key cleared.",
        "OpenAI API key saved.": "OpenAI API key saved.",
        "OpenAI API key stored in Keychain.": "OpenAI API key stored in Keychain.",
        "Open Pipelines": "Open Pipelines",
        "Open Release": "Open Release",
        "Open Releases": "Open Releases",
        "Open repository in browser": "Open repository in browser",
        "Open Tags": "Open Tags",
        "Open in Finder": "Open in Finder",
        "Open in GitLab": "Open in GitLab",
        "Open in Terminal": "Open in Terminal",
        "Other GitLab clients may still work if they use a different token, but the same user quota can still be shared.": "Other GitLab clients may still work if they use a different token, but the same user quota can still be shared.", // swiftlint:disable:this line_length
        "Other Resources": "Other Resources",
        "Paste key": "Paste key",
        "Personal Access Token": "Personal Access Token",
        "Pin": "Pin",
        "Pin a repository to see activity here.": "Pin a repository to see activity here.",
        "Pin/Unpin": "Pin/Unpin",
        "Pinned": "Pinned",
        "Pinned/hidden filter chips": "Pinned/hidden filter chips",
        "Pipelines": "Pipelines",
        "Preferences": "Preferences",
        "Preferences…": "Preferences…",
        "Preview truncated": "Preview truncated",
        "Provider": "Provider",
        "Rate limited until %@": "Rate limited until %@",
        "Rate limit reset: %@": "Rate limit reset: %@",
        "Rate limit resets %@": "Rate limit resets %@",
        "Rate-limit or error banner": "Rate-limit or error banner",
        "Rebase": "Rebase",
        "Rebase failed": "Rebase failed",
        "Quit RepoPeek": "Quit RepoPeek",
        "Recently active": "Recently active",
        "Release %@": "Release %@",
        "Releases": "Releases",
        "Remove": "Remove",
        "Remove Rule": "Remove Rule",
        "Repositories": "Repositories",
        "REST Core": "REST Core",
        "REST Search": "REST Search",
        "Repository Cards": "Repository Cards",
        "Repository List": "Repository List",
        "Repository name": "Repository name",
        "Repositories shown": "Repositories shown",
        "Repo cards + inline heatmap": "Repo cards + inline heatmap",
        "Repository rows + inline heatmap": "Repository rows + inline heatmap",
        "Repo heatmap submenu": "Repo heatmap submenu",
        "Repo Submenu": "Repo Submenu",
        "Repository heatmap": "Repository heatmap",
        "Repository heatmaps show recent commit activity for each repository.": "Repository heatmaps show recent commit activity for each repository.",
        "Request URL": "Request URL",
        "Request URL must be a valid http:// or https:// URL.": "Request URL must be a valid http:// or https:// URL.",
        "Required GitLab scopes: api, read_user, read_repository": "Required GitLab scopes: api, read_user, read_repository",
        "Required": "Required",
        "Required · %@": "Required · %@",
        "Reset": "Reset",
        "Reset failed": "Reset failed",
        "Reset to Defaults": "Reset to Defaults",
        "reset %@": "reset %@",
        "resets %@": "resets %@",
        "Restart to Update": "Restart to Update",
        "Restart to update": "Restart to update",
        "Reviewed": "Reviewed",
        "Review requested": "Review requested",
        "retry %@": "retry %@",
        "Save Account": "Save Account",
        "sampled %@": "sampled %@",
        "Settings": "Settings",
        "Set a local projects folder": "Set a local projects folder",
        "Search, filters, sort, and refresh": "Search, filters, sort, and refresh",
        "Scoped to pinned repositories. The first refresh records the current state without sending notifications.": "Scoped to pinned repositories. The first refresh records the current state without sending notifications.", // swiftlint:disable:this line_length
        "Shared GitLab user budget; RepoPeek and other PATs for this account can spend this API quota. Extra tokens do not create extra user quota.": "Shared GitLab user budget; RepoPeek and other PATs for this account can spend this API quota. Extra tokens do not create extra user quota.", // swiftlint:disable:this line_length
        "Show contribution header": "Show contribution header",
        "Show GitLab rate-limit count in menu bar": "Show GitLab rate-limit count in menu bar",
        "Show fewer repositories": "Show fewer repositories",
        "Show more repositories": "Show more repositories",
        "Show only my repositories": "Show only my repositories",
        "Shown only when GitLab API is blocked": "Shown only when GitLab API is blocked",
        "Shown when an update is ready": "Shown when an update is ready",
        "Sign In": "Sign In",
        "Sign in to GitLab": "Sign in to GitLab",
        "Sign in to load changelog": "Sign in to load changelog",
        "Sign in to load branches": "Sign in to load branches",
        "Sign in to load items": "Sign in to load items",
        "Sign in to see your repositories": "Sign in to see your repositories",
        "Sign in to view": "Sign in to view",
        "Signing in...": "Signing in...",
        "Signing in…": "Signing in…",
        "Sort by %@": "Sort by %@",
        "Sort by %@. Click to cycle.": "Sort by %@. Click to cycle.",
        "Stars": "Stars",
        "Status Banner": "Status Banner",
        "Stored Blockers": "Stored Blockers",
        "Switch Worktree": "Switch Worktree",
        "Switch branch failed": "Switch branch failed",
        "Sync": "Sync",
        "Sync + dirty state": "Sync + dirty state",
        "Sync failed": "Sync failed",
        "Submenu": "Submenu",
        "System": "System",
        "System accent": "System accent",
        "Tags": "Tags",
        "This will discard uncommitted changes and reset to %@.": "This will discard uncommitted changes and reset to %@.",
        "Timed out": "Timed out",
        "Timed out after %@s": "Timed out after %@s",
        "Token": "Token",
        "Token invalid: %@": "Token invalid: %@",
        "Token is valid.": "Token is valid.",
        "Token status not checked yet.": "Token status not checked yet.",
        "Tracking %@": "Tracking %@",
        "Try All or a different filter.": "Try All or a different filter.",
        "Updating repositories…": "Updating repositories…",
        "Updating…": "Updating…",
        "Update diagnostics copied.": "Update diagnostics copied.",
        "Use default request URL": "Use default request URL",
        "Uses Claude Agent CLI to summarize merge requests in Issue Navigator.": "Uses Claude Agent CLI to summarize merge requests in Issue Navigator.",
        "Uses local Claude Agent CLI authentication.": "Uses local Claude Agent CLI authentication.",
        "Uses OpenAI-compatible API to summarize merge requests in Issue Navigator.": "Uses OpenAI-compatible API to summarize merge requests in Issue Navigator.",
        "Using custom request URL: %@": "Using custom request URL: %@",
        "Using default request URL: %@": "Using default request URL: %@",
        "Unpin": "Unpin",
        "Updated %@": "Updated %@",
        "Upstream %@": "Upstream %@",
        "Visible": "Visible",
        "View All": "View All",
        "When clicked": "When clicked",
        "Work": "Work",
        "Worktree %@": "Worktree %@",
        "Worktree folder": "Worktree folder",
        "Worktree list failed": "Worktree list failed",
        "Worktree missing": "Worktree missing",
        "1 minute": "1 minute",
        "2 minutes": "2 minutes",
        "5 minutes": "5 minutes",
        "15 minutes": "15 minutes",
        "30 minutes": "30 minutes",
        "1 hour": "1 hour",
        "6 hours": "6 hours",
        "12 hours": "12 hours",
        "1 day": "1 day",
        "%d level": "%d level",
        "%d levels": "%d levels",
        "%d of %d repositories, %d pinned, %d hidden": "%d of %d repositories, %d pinned, %d hidden",
        "%d repositories, %d loaded, %d pinned, %d hidden": "%d repositories, %d loaded, %d pinned, %d hidden",
        "%d rows": "%d rows",
        "%@ issues": "%@ issues",
        "Action": "Action",
        "Add Repo": "Add Repo",
        "Add Rule": "Add Rule",
        "Activity %@": "Activity %@",
        "Archived": "Archived",
        "Auto-sync clean repos": "Auto-sync clean repos",
        "Branch %@": "Branch %@",
        "Browse repositories RepoPeek can access and choose what stays pinned or hidden.": "Browse repositories RepoPeek can access and choose what stays pinned or hidden.", // swiftlint:disable:this line_length
        "Built %@": "Built %@",
        "Check for updates automatically": "Check for updates automatically",
        "Check for Updates…": "Check for Updates…",
        "Choose": "Choose",
        "Choose…": "Choose…",
        "Choose Repo…": "Choose Repo…",
        "Change expression less often": "Change expression less often",
        "Change expression more often": "Change expression more often",
        "Clear project folder": "Clear project folder",
        "Clear search": "Clear search",
        "Cloners": "Cloners",
        "Controls how often idle menu bar icon expressions change.": "Controls how often idle menu bar icon expressions change.",
        "Controls how often RepoPeek refreshes GitLab data.": "Controls how often RepoPeek refreshes GitLab data.",
        "Debug": "Debug",
        "Developer-only diagnostics and experimental tools.": "Developer-only diagnostics and experimental tools.",
        "Enable debug tools": "Enable debug tools",
        "Enter group path": "Enter group path",
        "Enter group/subgroup before adding a rule.": "Enter group/subgroup before adding a rule.",
        "Enter owner/name before adding a rule.": "Enter owner/name before adding a rule.",
        "Enter repo name": "Enter repo name",
        "Engagement": "Engagement",
        "Fetch interval": "Fetch interval",
        "Fork": "Fork",
        "Found %d local repos · %d match GitLab data.": "Found %d local repos · %d match GitLab data.",
        "Found %d local repos.": "Found %d local repos.",
        "Ghostty opens in": "Ghostty opens in",
        "GitLab Archives": "GitLab Archives",
        "GitLab References": "GitLab References",
        "GitLab URLs, issue numbers, commit hashes": "GitLab URLs, issue numbers, commit hashes",
        "Group": "Group",
        "Group Hidden": "Group Hidden",
        "Group path": "Group path",
        "Group Rule": "Group Rule",
        "Hidden": "Hidden",
        "Hide Group": "Hide Group",
        "Hide Repository": "Hide Repository",
        "imported %@": "imported %@",
        "Local Projects": "Local Projects",
        "Manual": "Manual",
        "Matches": "Matches",
        "Menubar glance at GitLab repos: CI, issues/MRs, releases, and activity.": "Menubar glance at GitLab repos: CI, issues/MRs, releases, and activity.",
        "Merge requests %d": "Merge requests %d",
        "New Window": "New Window",
        "No GitLab archives configured.": "No GitLab archives configured.",
        "No repositories found yet. Re-choose the folder to grant access.": "No repositories found yet. Re-choose the folder to grant access.",
        "No repositories found yet.": "No repositories found yet.",
        "Not set": "Not set",
        "not ready": "not ready",
        "now": "now",
        "group/subgroup": "group/subgroup",
        "owner/name": "owner/name",
        "owner/repo, URL, or local path": "owner/repo, URL, or local path",
        "Pin a repository": "Pin a repository",
        "Pin Repository": "Pin Repository",
        "Pipeline %@": "Pipeline %@",
        "Point RepoPeek at a snapshot repository. RepoPeek manages the imported database internally and uses it only when GitLab is rate limited.": "Point RepoPeek at a snapshot repository. RepoPeek manages the imported database internally and uses it only when GitLab is rate limited.", // swiftlint:disable:this line_length
        "Preferred Terminal": "Preferred Terminal",
        "Press shortcut": "Press shortcut",
        "Project folder": "Project folder",
        "Pull and import archive": "Pull and import archive",
        "pushed %@": "pushed %@",
        "ready": "ready",
        "Refresh": "Refresh",
        "Refresh interval": "Refresh interval",
        "Refresh Now": "Refresh Now",
        "Remove archive": "Remove archive",
        "Repo": "Repo",
        "repo: %@": "repo: %@",
        "Repository": "Repository",
        "Repository path": "Repository path",
        "Repository rules use owner/name. Group rules use namespace paths such as group/subgroup and hide everything below that path.": "Repository rules use owner/name. Group rules use namespace paths such as group/subgroup and hide everything below that path.", // swiftlint:disable:this line_length
        "Rule": "Rule",
        "Rule Type": "Rule Type",
        "Rules use owner/name. Pinned repositories are prioritized in the menu; hidden repositories are removed from menu lists. Set Visible removes a rule.": "Rules use owner/name. Pinned repositories are prioritized in the menu; hidden repositories are removed from menu lists. Set Visible removes a rule.", // swiftlint:disable:this line_length
        "Rescan local projects": "Rescan local projects",
        "Scope": "Scope",
        "Scan depth": "Scan depth",
        "Scanning…": "Scanning…",
        "Scans up to the configured depth under the folder, fetches periodically, and can fast-forward pull clean repos.": "Scans up to the configured depth under the folder, fetches periodically, and can fast-forward pull clean repos.", // swiftlint:disable:this line_length
        "Save": "Save",
        "Search current list": "Search current list",
        "Search repositories": "Search repositories",
        "Set Visible": "Set Visible",
        "sec.": "sec.",
        "Show dirty files in menu": "Show dirty files in menu",
        "Shows the best cached or live match in a separate menu bar item when a copied reference resolves.": "Shows the best cached or live match in a separate menu bar item when a copied reference resolves.", // swiftlint:disable:this line_length
        "Shortcuts": "Shortcuts",
        "Summarize merge requests": "Summarize merge requests",
        "Summarizing merge requests…": "Summarizing merge requests…",
        "Status icon expression": "Status icon expression",
        "Sync %@": "Sync %@",
        "Tab": "Tab",
        "Updates unavailable in this build.": "Updates unavailable in this build.",
        "Updated": "Updated",
        "Uses OpenAI Responses API to summarize merge requests in Issue Navigator.": "Uses OpenAI Responses API to summarize merge requests in Issue Navigator.",
        "Use archives when rate limited": "Use archives when rate limited",
        "Version %@": "Version %@",
        "Visibility": "Visibility",
        "Visitors": "Visitors",
        "Watch copied GitLab references": "Watch copied GitLab references",
        "All Repositories": "All Repositories",
        "Back": "Back",
        "Clipboard: %@": "Clipboard: %@",
        "Closed": "Closed",
        "Copy": "Copy",
        "Copy selected result URL": "Copy selected result URL",
        "Commit": "Commit",
        "Copy URL": "Copy URL",
        "Draft": "Draft",
        "Issue": "Issue",
        "Issues + MRs": "Issues + MRs",
        "Issue Navigator shortcut": "Issue Navigator shortcut",
        "Items": "Items",
        "Keyboard Shortcuts": "Keyboard Shortcuts",
        "Loading recent issues and merge requests.": "Loading recent issues and merge requests.",
        "match": "match",
        "matches": "matches",
        "None": "None",
        "Merged": "Merged",
        "Merge Request": "Merge Request",
        "No matches": "No matches",
        "No matching issues or merge requests.": "No matching issues or merge requests.",
        "No recent issues or merge requests in this scope.": "No recent issues or merge requests in this scope.",
        "No recent items in this scope.": "No recent items in this scope.",
        "Open": "Open",
        "Open in Browser": "Open in Browser",
        "Open selected result in browser": "Open selected result in browser",
        "Pick a result": "Pick a result",
        "Pre": "Pre",
        "Recent subscribed and accessible items": "Recent subscribed and accessible items",
        "References in pasted order": "References in pasted order",
        "Refresh results": "Refresh results",
        "Search by title, URL, owner/repo#number, or commit SHA.": "Search by title, URL, owner/repo#number, or commit SHA.",
        "Search failed": "Search failed",
        "Search the current clipboard reference": "Search the current clipboard reference",
        "Search issues and merge requests": "Search issues and merge requests",
        "Searching…": "Searching…",
        "Showing recent items; type at least %d characters to search.": "Showing recent items; type at least %d characters to search.",
        "Type at least %d characters, or paste a GitLab reference.": "Type at least %d characters, or paste a GitLab reference.",
        "Updated newest first": "Updated newest first",
        "Using %@": "Using %@",
        "Use Clipboard": "Use Clipboard",
        "Workflow Run": "Workflow Run",
        "Work GitLab": "Work GitLab"
    ]
}
